web:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

api:
    resource:
        path: ../src/Controller/Api
        namespace: App\Controller\Api
    type: attribute
    prefix: '/api' # Préfixe pour les routes API
    name_prefix: 'api_' # Préfixe pour les noms des routes API

